[package]
name = "contour"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "^0.8.0" }
bevy_egui = "^0.15.1"
bevy-inspector-egui = "^0.12.1"
bevy_rapier2d = { version = "^0.16.0", features = [
    "simd-stable",
    "debug-render",
] }
bevy_ecs_tilemap = "0.7.0"
rand = "^0.8.5"

[profile.dev.package."*"]
opt-level = 3